config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-amaranth-burmese.sh
        container: qc.acc_shaky-cerulean-collie
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-sepia-tetra.sh
        container: qc.doc_blurry-pear-dollar
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cream-akita.sh
        container: qc.doc_sleepy-green-beagle
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-malachite-ibis.sh
        container: qc.doc_cloudy-cobalt-armadillo
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-copper-sheep.sh
        container: qc.lic_muzzy-harlequin-mole
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-cerise-dodo.sh
        container: qc.met_boozy-auburn-dollar
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-sangria-drever.sh
        container: qc.sec_stinky-aquamarine-fox
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-scarlet-cougar.sh
        container: qc.sty_scaly-olivine-gerbil
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-alizarin-earwig.sh
        container: qc.sty_crappy-magnolia-javanese
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-viridian-macaw.sh
        container: qc.ver_fuzzy-scarlet-crab
timeout: 1800
