config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-buff-gharial.sh
        container: qc.acc_zippy-firebrick-snail
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-orchid-cuttlefish.sh
        container: qc.doc_bumpy-corn-guppy
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-puce-yak.sh
        container: qc.doc_shabby-apricot-caterpillar
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-amethyst-oriole.sh
        container: qc.doc_boozy-chocolate-wolf
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-lavender-olm.sh
        container: qc.lic_smelly-cinnabar-capuchin
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-alizarin-husky.sh
        container: qc.met_frumpy-jade-toad
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-jade-mayfly.sh
        container: qc.sec_seedy-taupe-dog
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-saffron-nightingale.sh
        container: qc.sty_scaly-celadon-capybara
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-platinum-mist.sh
        container: qc.ver_silly-celadon-fish
timeout: 1800
