config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-zucchini-booby.sh
        container: qc.acc_hazy-cerise-elephant
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-sangria-emu.sh
        container: qc.doc_wheezy-russet-quoll
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-pink-goat.sh
        container: qc.doc_flabby-cyan-bongo
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-khaki-goat.sh
        container: qc.doc_dorky-khaki-gopher
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-red-collie.sh
        container: qc.lic_ugly-chestnut-dane
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-tomato-goat.sh
        container: qc.met_fuzzy-amethyst-collie
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-vermilion-antelope.sh
        container: qc.sec_stealthy-khaki-nightingale
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cerulean-javanese.sh
        container: qc.sty_trippy-beige-hyena
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-fuchsia-monster.sh
        container: qc.ver_clammy-ecru-scorpion
timeout: 1800
