config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cream-bat.sh
        container: qc.acc_hasty-aqua-badger
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-tan-wolf.sh
        container: qc.doc_slimy-smalt-wasp
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-crimson-dolphin.sh
        container: qc.doc_chummy-bronze-woodlouse
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-celadon-anteater.sh
        container: qc.doc_scanty-myrtle-ladybird
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cardinal-husky.sh
        container: qc.lic_pasty-tomato-toad
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-goldenrod-dachshund.sh
        container: qc.met_tasty-cardinal-mouse
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-teal-dalmatian.sh
        container: qc.sec_scaly-smalt-deer
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cornflower-butterfly.sh
        container: qc.sty_snippy-copper-retriever
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-carmine-lizard.sh
        container: qc.sty_flaky-ecru-mammoth
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-corn-olm.sh
        container: qc.ver_breezy-heliotrope-balinese
timeout: 5400
