config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-corn-abyssinian.sh
        container: qc.acc_flaky-scarlet-wasp
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-violet-armadillo.sh
        container: qc.doc_skinny-cinnabar-husky
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-mustard-budgerigar.sh
        container: qc.doc_thirsty-lime-hamster
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-lemon-peccary.sh
        container: qc.doc_skimpy-charcoal-fowl
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-periwinkle-hippopotamus.sh
        container: qc.lic_breezy-razzmatazz-affenpinscher
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-yellow-hound.sh
        container: qc.met_homely-khaki-coral
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cerise-bulldog.sh
        container: qc.sec_sloppy-russet-moose
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-jade-barnacle.sh
        container: qc.sty_beady-xanthic-insect
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-coral-octopus.sh
        container: qc.ver_hilly-chartreuse-setter
timeout: 1800
