config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lavender-squirt.sh
        container: qc.acc_squeaky-buff-octopus
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-thistle-liger.sh
        container: qc.doc_breezy-cerise-moose
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-viridian-hamster.sh
        container: qc.doc_droopy-salmon-gar
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-xanthic-coyote.sh
        container: qc.doc_grumpy-grey-moorhen
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-lilac-goose.sh
        container: qc.lic_woolly-tangerine-termite
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-teal-capybara.sh
        container: qc.met_whiny-sepia-barracuda
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-wheat-vole.sh
        container: qc.sec_wheezy-charcoal-capuchin
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-crimson-uakari.sh
        container: qc.sty_homey-periwinkle-llama
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-amber-neanderthal.sh
        container: qc.sty_woozy-burgundy-mouse
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-lemon-raccoon.sh
        container: qc.ver_ugly-sangria-cat
timeout: 1800
