config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-chartreuse-fossa.sh
        container: qc.acc_snazzy-cyan-husky
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-lemon-blue.sh
        container: qc.doc_bluesy-magenta-beagle
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-wisteria-hedgehog.sh
        container: qc.doc_chummy-pear-corgi
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-red-catfish.sh
        container: qc.doc_muzzy-chocolate-skunk
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-pear-kiwi.sh
        container: qc.lic_tasty-coral-grouse
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-malachite-discus.sh
        container: qc.met_hasty-chartreuse-bombay
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cobalt-peccary.sh
        container: qc.sec_sunny-viridian-magpie
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-chocolate-crane.sh
        container: qc.sty_droopy-cornflower-quokka
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-indigo-fousek.sh
        container: qc.sty_seedy-heliotrope-cat
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-bronze-mist.sh
        container: qc.ver_breezy-pink-otter
timeout: 1800
