config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: ''
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker:
        commands:
        - /usr/bin/env sh .sqa/script.randy-jade-otter.sh
        container: qc.acc_gummy-heliotrope-dalmatian
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-sapphire-badger.sh
        container: qc.doc_silly-smalt-dollar
      github.com/indigo-dc/udocker__2:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cream-mastiff.sh
        container: qc.doc_sickly-purple-reindeer
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-carmine-dragon.sh
        container: qc.lic_gloppy-cornflower-pig
  QC.Met:
    repos:
      github.com/indigo-dc/udocker:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-harlequin-ibis.sh
        container: qc.met_pasty-purple-orangutan
timeout: 600
