config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-crimson-mouse.sh
        container: qc.acc_hazy-chestnut-dugong
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-bistre-ant.sh
        container: qc.doc_leaky-heliotrope-horse
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-salmon-hornet.sh
        container: qc.doc_snoopy-cornflower-quokka
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-myrtle-dragonfly.sh
        container: qc.doc_cheeky-crimson-mau
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-black-deer.sh
        container: qc.lic_surly-copper-angora
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-scarlet-bordeaux.sh
        container: qc.met_gummy-grey-cuscus
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-viridian-deer.sh
        container: qc.sec_craggy-lavender-bird
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-scarlet-dormouse.sh
        container: qc.sty_geeky-magenta-slug
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-maroon-abyssinian.sh
        container: qc.ver_thirsty-fuchsia-neanderthal
timeout: 1800
