config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-turquoise-chameleon.sh
        container: qc.acc_ready-ultramarine-beetle
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-viridian-macaque.sh
        container: qc.doc_gimpy-ultramarine-koala
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-emerald-lionfish.sh
        container: qc.doc_nippy-mustard-drever
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-celadon-weasel.sh
        container: qc.doc_flabby-maroon-corgi
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-teal-setter.sh
        container: qc.lic_woolly-gold-buzzard
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-eggplant-bobcat.sh
        container: qc.met_baggy-mustard-hyena
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-aquamarine-neanderthal.sh
        container: qc.sec_cheeky-mauve-dachshund
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-teal-kakapo.sh
        container: qc.sty_squirrely-amber-forest
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-platinum-drever.sh
        container: qc.sty_whiny-purple-fly
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-taupe-quetzal.sh
        container: qc.ver_lanky-aquamarine-armadillo
timeout: 5400
