config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-amaranth-tarantula.sh
        container: qc.acc_leaky-coral-guppy
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-amethyst-tang.sh
        container: qc.doc_tasty-teal-chinchilla
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-harlequin-sheep.sh
        container: qc.doc_pasty-goldenrod-flounder
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-champagne-eel.sh
        container: qc.doc_snappy-cyan-dunker
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-xanthic-bee.sh
        container: qc.lic_gloppy-amber-mongoose
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-lilac-rhinoceros.sh
        container: qc.met_gummy-amaranth-snail
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-pink-devil.sh
        container: qc.sec_randy-peach-foxhound
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-bronze-greyhound.sh
        container: qc.sty_chummy-red-chow
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-peach-labradoodle.sh
        container: qc.sty_muzzy-firebrick-iguana
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cobalt-ray.sh
        container: qc.ver_frumpy-lemon-chamois
timeout: 1800
