config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cerise-chicken.sh
        container: qc.acc_lumpy-tomato-moose
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-firebrick-eagle.sh
        container: qc.doc_cranky-emerald-hornet
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-amber-crane.sh
        container: qc.doc_sloppy-asparagus-turtle
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-auburn-fish.sh
        container: qc.doc_tacky-turquoise-squirrel
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-azure-mastiff.sh
        container: qc.lic_boozy-saffron-flamingo
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-zucchini-clam.sh
        container: qc.met_nippy-tangerine-hound
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-mauve-moorhen.sh
        container: qc.sec_sleepy-platinum-gerbil
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-denim-wolfhound.sh
        container: qc.sty_crabby-fuchsia-alligator
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-heliotrope-eel.sh
        container: qc.sty_snoopy-silver-uakari
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-amethyst-peccary.sh
        container: qc.ver_tasty-bistre-jellyfish
timeout: 1800
