config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: dev-v1.4
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-red-cichlid.sh
        container: qc.acc_snippy-goldenrod-drever
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-champagne-husky.sh
        container: qc.doc_lumpy-olivine-zorse
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-malachite-discus.sh
        container: qc.doc_pretty-chartreuse-lynx
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-taupe-whippet.sh
        container: qc.doc_boozy-purple-wallaby
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-magnolia-rat.sh
        container: qc.lic_slimy-silver-tiger
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-charcoal-tarantula.sh
        container: qc.met_homey-bronze-russel
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-maroon-guppy.sh
        container: qc.sec_tasty-carmine-grasshopper
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-lime-orangutan.sh
        container: qc.sty_woozy-gold-hummingbird
      github.com/indigo-dc/udocker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cerise-tortoise.sh
        container: qc.sty_muzzy-emerald-snake
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-harlequin-penguin.sh
        container: qc.sty_tacky-amber-axolotl
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-wheat-uakari.sh
        container: qc.ver_stealthy-copper-numbat
timeout: 5400
