config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-khaki-bordeaux.sh
        container: qc.acc_sickly-cornflower-caracal
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-lavender-dane.sh
        container: qc.doc_zippy-xanthic-yak
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-charcoal-saola.sh
        container: qc.doc_woolly-lavender-gibbon
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-lavender-cougar.sh
        container: qc.doc_dorky-ecru-dalmatian
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cinnabar-zebu.sh
        container: qc.lic_gummy-gold-koala
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-mauve-beagle.sh
        container: qc.met_cozy-mustard-shrew
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-lilac-avocet.sh
        container: qc.sec_lanky-cerulean-capybara
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cream-sloth.sh
        container: qc.sty_queasy-bistre-lobster
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-emerald-crocodile.sh
        container: qc.sty_skimpy-cinnabar-axolotl
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-lime-forest.sh
        container: qc.ver_pokey-ivory-earwig
timeout: 1800
