config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-ochre-gopher.sh
        container: qc.acc_skimpy-razzmatazz-caterpillar
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-alizarin-worm.sh
        container: qc.doc_fuzzy-ivory-balinese
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cinnabar-beaver.sh
        container: qc.doc_leaky-buff-mandrill
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ultramarine-crocodile.sh
        container: qc.doc_zippy-bronze-moth
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-violet-mau.sh
        container: qc.lic_whiny-rust-indri
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-beige-terrier.sh
        container: qc.met_blurry-orchid-seal
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-thistle-beetle.sh
        container: qc.sec_geeky-thistle-skunk
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-lavender-markhor.sh
        container: qc.sty_snappy-firebrick-gecko
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-platinum-chameleon.sh
        container: qc.sty_squeaky-black-guppy
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-myrtle-bison.sh
        container: qc.ver_greasy-denim-iguana
timeout: 5400
