config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/udocker:
      branch: master
      repo: https://github.com/orviz/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/orviz/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-lime-fowl.sh
        container: qc.acc_hazy-olive-woodpecker
  QC.Doc:
    repos:
      github.com/orviz/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-turquoise-butterfly.sh
        container: qc.doc_slimy-russet-bee
      github.com/orviz/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-tomato-kudu.sh
        container: qc.doc_chummy-brass-vole
      github.com/orviz/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-smalt-tiger.sh
        container: qc.doc_muggy-beige-earwig
  QC.Lic:
    repos:
      github.com/orviz/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-azure-quoll.sh
        container: qc.lic_breezy-denim-discus
  QC.Met:
    repos:
      github.com/orviz/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-magnolia-ragdoll.sh
        container: qc.met_frumpy-amaranth-donkey
  QC.Sec:
    repos:
      github.com/orviz/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-lilac-crane.sh
        container: qc.sec_sunny-orchid-duck
  QC.Sty:
    repos:
      github.com/orviz/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-lilac-tapir.sh
        container: qc.sty_blurry-violet-gopher
      github.com/orviz/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cyan-okapi.sh
        container: qc.sty_skinny-harlequin-chimpanzee
  QC.Ver:
    repos:
      github.com/orviz/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cinnamon-centipede.sh
        container: qc.ver_nerdy-orange-fox
timeout: 5400
