config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: dev-v1.4
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-platinum-vulture.sh
        container: qc.acc_baggy-cerulean-starfish
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-maroon-russel.sh
        container: qc.doc_smelly-celadon-robin
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-aqua-slug.sh
        container: qc.doc_queasy-viridian-quetzal
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-taupe-woodlouse.sh
        container: qc.doc_randy-persimmon-dhole
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-salmon-leopard.sh
        container: qc.lic_messy-cyan-chameleon
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.randy-orchid-mammoth.sh
        container: qc.met_ready-ochre-monkey
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-amethyst-mayfly.sh
        container: qc.sec_snoopy-flax-grouse
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-plum-hound.sh
        container: qc.sty_messy-yellow-moorhen
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-platinum-devil.sh
        container: qc.ver_snippy-salmon-tarsier
timeout: 1800
