config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-amaranth-bloodhound.sh
        container: qc.acc_pokey-myrtle-tamarin
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-alizarin-shrew.sh
        container: qc.doc_dorky-lemon-robin
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-alizarin-mule.sh
        container: qc.doc_gloppy-persimmon-tortoise
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-sepia-badger.sh
        container: qc.doc_fuzzy-malachite-tarantula
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-silver-moose.sh
        container: qc.lic_freaky-platinum-fox
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.homey-xanthic-rhinoceros.sh
        container: qc.met_hasty-tangerine-loon
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cinnamon-wolf.sh
        container: qc.sec_squirrely-rose-bloodhound
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-tan-pinscher.sh
        container: qc.sty_sunny-tan-russel
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-alizarin-tetra.sh
        container: qc.sty_scummy-taupe-akbash
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cyan-woodpecker.sh
        container: qc.ver_thirsty-amethyst-dolphin
timeout: 1800
