config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cream-yak.sh
        container: qc.acc_boozy-plum-armadillo
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-silver-forest.sh
        container: qc.doc_flimsy-ochre-hummingbird
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cyan-seal.sh
        container: qc.doc_woolly-wisteria-wasp
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-periwinkle-tiger.sh
        container: qc.doc_pokey-corn-vole
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-dandelion-owl.sh
        container: qc.lic_snazzy-heliotrope-spider
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-myrtle-squid.sh
        container: qc.met_pokey-amethyst-maltese
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cornflower-boar.sh
        container: qc.sec_sleazy-rose-dachsbracke
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-lime-saola.sh
        container: qc.sty_skimpy-burgundy-horse
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-amethyst-gopher.sh
        container: qc.ver_tasty-ultramarine-dugong
timeout: 1800
