config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-tan-argentino.sh
        container: qc.acc_woozy-buff-magpie
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-puce-falcon.sh
        container: qc.doc_shaky-heliotrope-wallaby
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-grey-chameleon.sh
        container: qc.doc_bluesy-xanthic-centipede
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-xanthic-indri.sh
        container: qc.doc_whiny-magnolia-tetra
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-brown-weasel.sh
        container: qc.lic_whiny-green-baboon
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-ivory-zorse.sh
        container: qc.met_bumpy-salmon-goose
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-heliotrope-spaniel.sh
        container: qc.sec_beady-seashell-fish
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-brass-numbat.sh
        container: qc.sty_squirrely-sapphire-frise
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-flax-pinscher.sh
        container: qc.sty_lanky-cyan-worm
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-teal-fowl.sh
        container: qc.ver_bumpy-cinnamon-flamingo
timeout: 1800
