config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-heliotrope-jackal.sh
        container: qc.acc_sleepy-wisteria-eel
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-sepia-rhinoceros.sh
        container: qc.doc_hilly-lime-spaniel
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-aqua-tang.sh
        container: qc.doc_stealthy-cerise-macaw
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-tangerine-turtle.sh
        container: qc.doc_bumpy-chestnut-impala
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-salmon-vole.sh
        container: qc.lic_clammy-cornflower-wrasse
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-rust-barb.sh
        container: qc.met_chummy-goldenrod-tiger
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-magenta-octopus.sh
        container: qc.sec_droopy-platinum-penguin
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-amethyst-affenpinscher.sh
        container: qc.sty_slimy-rose-bulldog
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-orchid-setter.sh
        container: qc.sty_thirsty-dandelion-butterfly
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-puce-kakapo.sh
        container: qc.ver_pokey-wheat-squirrel
timeout: 1800
