config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-beige-collie.sh
        container: qc.acc_gamy-lime-chinook
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-copper-ocelot.sh
        container: qc.doc_slaphappy-burgundy-chihuahua
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-asparagus-cat.sh
        container: qc.doc_boozy-salmon-bobcat
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-tan-sparrow.sh
        container: qc.doc_tasty-ultramarine-baboon
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-ecru-dolphin.sh
        container: qc.lic_snippy-ecru-beetle
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-burgundy-chameleon.sh
        container: qc.met_gimpy-vermilion-hedgehog
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-silver-gerbil.sh
        container: qc.sec_snippy-thistle-ray
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-emerald-llama.sh
        container: qc.sty_smelly-myrtle-birman
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-saffron-cow.sh
        container: qc.sty_pasty-brown-urchin
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ochre-koala.sh
        container: qc.ver_slimy-brown-cow
timeout: 1800
