config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-lime-woodlouse.sh
        container: qc.acc_breezy-buff-raccoon
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-ivory-gecko.sh
        container: qc.doc_stuffy-salmon-zonkey
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-apricot-orangutan.sh
        container: qc.doc_lovely-orchid-maltese
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-bronze-flounder.sh
        container: qc.doc_tasty-viridian-dog
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-chocolate-zebu.sh
        container: qc.lic_hilly-myrtle-corgi
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-periwinkle-cuscus.sh
        container: qc.met_bluesy-sepia-kudu
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cerise-mule.sh
        container: qc.sec_droopy-flax-vole
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-pear-eagle.sh
        container: qc.sty_surly-coral-coati
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-linen-saola.sh
        container: qc.sty_wimpy-razzmatazz-hyena
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-ultramarine-kangaroo.sh
        container: qc.ver_messy-aqua-whale
timeout: 5400
