config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-buff-terrier.sh
        container: qc.acc_shaggy-cyan-flamingo
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-indigo-indri.sh
        container: qc.doc_boozy-denim-duck
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-grey-barb.sh
        container: qc.doc_snippy-salmon-budgerigar
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-alizarin-tarsier.sh
        container: qc.doc_cozy-plum-cassowary
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-dandelion-mongoose.sh
        container: qc.lic_paltry-orchid-avocet
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-indigo-kangaroo.sh
        container: qc.met_woolly-charcoal-slug
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-orchid-hyrax.sh
        container: qc.sec_wiggy-dandelion-chinchilla
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-teal-cat.sh
        container: qc.sty_randy-yellow-stingray
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-black-mammoth.sh
        container: qc.sty_squirrely-purple-cichlid
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-turquoise-kakapo.sh
        container: qc.ver_squeaky-denim-moose
timeout: 1800
