config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/udocker:
      branch: master
      repo: https://github.com/orviz/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/orviz/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-black-argentino.sh
        container: qc.acc_sunny-ochre-mouse
  QC.Doc:
    repos:
      github.com/orviz/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-aquamarine-ferret.sh
        container: qc.doc_ugly-saffron-shrew
      github.com/orviz/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-gold-uakari.sh
        container: qc.doc_scummy-alizarin-frise
      github.com/orviz/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-lime-crab.sh
        container: qc.doc_snoopy-lemon-bombay
  QC.Lic:
    repos:
      github.com/orviz/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-chartreuse-sponge.sh
        container: qc.lic_randy-maroon-hyena
  QC.Met:
    repos:
      github.com/orviz/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.silly-heliotrope-shark.sh
        container: qc.met_wiggy-ultramarine-eagle
  QC.Sec:
    repos:
      github.com/orviz/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-smalt-moose.sh
        container: qc.sec_paltry-viridian-macaw
  QC.Sty:
    repos:
      github.com/orviz/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-gold-lemming.sh
        container: qc.sty_bluesy-pear-birman
      github.com/orviz/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-sangria-starfish.sh
        container: qc.sty_lumpy-heliotrope-fly
  QC.Ver:
    repos:
      github.com/orviz/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-wisteria-salamander.sh
        container: qc.ver_snoopy-jade-wildebeest
timeout: 1800
