config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-aqua-squirrel.sh
        container: qc.acc_gamy-plum-guppy
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-plum-uguisu.sh
        container: qc.doc_muggy-vermilion-mandrill
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-linen-malamute.sh
        container: qc.doc_wheezy-khaki-retriever
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-pumpkin-ibis.sh
        container: qc.doc_foggy-zucchini-terrier
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-chestnut-cheetah.sh
        container: qc.lic_hasty-indigo-caracal
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-periwinkle-chicken.sh
        container: qc.met_wiggy-gold-butterfly
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-russet-kiwi.sh
        container: qc.sec_queasy-orchid-bison
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-vermilion-bombay.sh
        container: qc.sty_pasty-grey-eagle
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-chestnut-bison.sh
        container: qc.sty_messy-ruby-cuttlefish
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-linen-mist.sh
        container: qc.ver_smelly-harlequin-cattle
timeout: 1800
