config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-white-mist.sh
        container: qc.acc_tacky-zucchini-uguisu
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-azure-bracke.sh
        container: qc.doc_bumpy-cinnamon-cockroach
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-persimmon-ragdoll.sh
        container: qc.doc_crabby-wisteria-dogfish
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-tangerine-blue.sh
        container: qc.doc_dorky-gold-flamingo
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-bronze-raccoon.sh
        container: qc.lic_crappy-vermilion-mongrel
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-violet-devil.sh
        container: qc.met_nerdy-purple-newfoundland
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-turquoise-ant.sh
        container: qc.sec_tacky-amber-olm
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ivory-dragon.sh
        container: qc.sty_randy-olive-barb
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-rose-lemur.sh
        container: qc.ver_cozy-amaranth-maltese
timeout: 1800
