config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-mustard-wolfhound.sh
        container: qc.acc_clammy-chocolate-lemur
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-xanthic-woodpecker.sh
        container: qc.doc_dorky-brass-meerkat
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-maroon-javanese.sh
        container: qc.doc_foggy-sepia-wolf
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-mustard-markhor.sh
        container: qc.doc_pretty-crimson-lobster
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-fuchsia-audemer.sh
        container: qc.lic_flaky-ochre-fly
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-ruby-alligator.sh
        container: qc.met_lumpy-smalt-walrus
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-goldenrod-alligator.sh
        container: qc.sec_scaly-smalt-quoll
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-green-swan.sh
        container: qc.sty_nippy-bistre-weasel
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-rose-chimpanzee.sh
        container: qc.sty_homey-firebrick-peccary
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-gamboge-uakari.sh
        container: qc.ver_droopy-pumpkin-eleuth
timeout: 5400
