config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-salmon-peccary.sh
        container: qc.acc_stuffy-ultramarine-insect
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-tangerine-kiwi.sh
        container: qc.doc_tacky-cinnamon-chinook
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-khaki-chicken.sh
        container: qc.doc_flabby-taupe-cuttlefish
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cobalt-fly.sh
        container: qc.doc_flimsy-gamboge-shark
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-magnolia-binturong.sh
        container: qc.lic_gloppy-flax-affenpinscher
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cinnabar-sponge.sh
        container: qc.met_craggy-lavender-dachshund
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-tangerine-bison.sh
        container: qc.sec_pokey-carmine-fousek
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-sangria-elephant.sh
        container: qc.sty_scummy-jade-tetra
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-charcoal-discus.sh
        container: qc.ver_geeky-rose-cougar
timeout: 1800
