config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-burgundy-meerkat.sh
        container: qc.acc_hasty-white-grasshopper
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-jade-jackal.sh
        container: qc.doc_flaky-azure-kangaroo
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ochre-mongoose.sh
        container: qc.doc_scanty-puce-malamute
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-brass-mandrill.sh
        container: qc.doc_flabby-lime-cougar
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-burgundy-turkey.sh
        container: qc.lic_lovely-crimson-fousek
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-pear-gorilla.sh
        container: qc.met_crabby-chartreuse-dollar
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-thistle-toucan.sh
        container: qc.sec_shaky-silver-forest
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-magnolia-antelope.sh
        container: qc.sty_foggy-turquoise-wolf
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-celadon-affenpinscher.sh
        container: qc.sty_flabby-lavender-snake
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-burgundy-insect.sh
        container: qc.ver_shabby-brass-fowl
timeout: 1800
