config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/udocker:
      branch: master
      repo: https://github.com/orviz/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/orviz/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-gamboge-akbash.sh
        container: qc.acc_scanty-blue-impala
  QC.Doc:
    repos:
      github.com/orviz/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-peach-rattlesnake.sh
        container: qc.doc_woolly-coral-caracal
      github.com/orviz/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-wheat-grouse.sh
        container: qc.doc_breezy-corn-lynx
      github.com/orviz/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ochre-crane.sh
        container: qc.doc_chummy-amethyst-axolotl
  QC.Lic:
    repos:
      github.com/orviz/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-olive-eleuth.sh
        container: qc.lic_freaky-wheat-setter
  QC.Met:
    repos:
      github.com/orviz/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-brown-slug.sh
        container: qc.met_wheezy-tomato-spitz
  QC.Sec:
    repos:
      github.com/orviz/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.randy-russet-rat.sh
        container: qc.sec_pokey-silver-kangaroo
  QC.Sty:
    repos:
      github.com/orviz/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-lemon-pig.sh
        container: qc.sty_jumpy-apricot-monster
      github.com/orviz/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-teal-tamarin.sh
        container: qc.sty_slimy-fuchsia-squirt
  QC.Ver:
    repos:
      github.com/orviz/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-orange-slug.sh
        container: qc.ver_baggy-aqua-macaque
timeout: 1800
