config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-amber-fish.sh
        container: qc.acc_grumpy-auburn-flounder
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-auburn-barb.sh
        container: qc.doc_cranky-tan-gopher
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cinnabar-akbash.sh
        container: qc.doc_fuzzy-seashell-seal
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-russet-capybara.sh
        container: qc.doc_surly-cerise-bonobo
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-coral-balinese.sh
        container: qc.lic_blurry-violet-tortoise
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-orchid-spaniel.sh
        container: qc.met_dorky-mauve-salamander
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-seashell-gharial.sh
        container: qc.sec_shaggy-yellow-chinook
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cornflower-warthog.sh
        container: qc.sty_beady-salmon-orangutan
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-puce-panda.sh
        container: qc.sty_jumpy-lavender-lynx
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-carmine-mammoth.sh
        container: qc.ver_tasty-coral-toucan
timeout: 5400
