config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: dev-v1.4
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-brass-bracke.sh
        container: qc.acc_clammy-cornflower-oriole
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-zucchini-retriever.sh
        container: qc.doc_snazzy-rose-macaw
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-viridian-corgi.sh
        container: qc.doc_muggy-bistre-donkey
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-pear-millipede.sh
        container: qc.doc_scaly-champagne-scorpion
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-turquoise-barracuda.sh
        container: qc.lic_slaphappy-amaranth-hamster
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-persimmon-sheep.sh
        container: qc.met_blurry-chestnut-earwig
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-jade-penguin.sh
        container: qc.sec_tasty-ecru-frigatebird
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-celadon-barnacle.sh
        container: qc.sty_hilly-blue-civet
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-harlequin-opossum.sh
        container: qc.ver_frumpy-aqua-discus
timeout: 1800
