config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-firebrick-otter.sh
        container: qc.acc_ready-razzmatazz-rattlesnake
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-cornflower-flounder.sh
        container: qc.doc_cozy-apricot-chicken
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-rose-bison.sh
        container: qc.doc_stinky-amber-wallaby
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-orchid-coral.sh
        container: qc.doc_cranky-lemon-dolphin
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-auburn-tiger.sh
        container: qc.lic_scummy-heliotrope-lemming
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-harlequin-crab.sh
        container: qc.met_shaky-cardinal-tapir
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-blue-vulture.sh
        container: qc.sec_snappy-cinnabar-rat
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-peach-javanese.sh
        container: qc.sty_skinny-pear-donkey
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-rose-quoll.sh
        container: qc.sty_tacky-cyan-macaque
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-red-snail.sh
        container: qc.ver_foggy-amaranth-hedgehog
timeout: 1800
