config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/bandit
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-sepia-bandicoot.sh
        container: qc.acc_seedy-jade-goose
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-purple-tzu.sh
        container: qc.doc_trippy-mauve-hyena
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-chocolate-malamute.sh
        container: qc.doc_breezy-red-husky
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-vermilion-koala.sh
        container: qc.lic_smelly-auburn-mouse
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-ecru-akita.sh
        container: qc.met_cheeky-pumpkin-mastiff
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-lemon-sponge.sh
        container: qc.sec_snazzy-dandelion-rhinoceros
timeout: 600
