config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-bistre-gar.sh
        container: qc.acc_muzzy-ecru-chameleon
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-yellow-wasp.sh
        container: qc.doc_snippy-celadon-cockroach
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-bronze-macaque.sh
        container: qc.doc_boozy-aqua-mole
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-harlequin-stoat.sh
        container: qc.doc_skimpy-white-audemer
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-xanthic-dugong.sh
        container: qc.lic_homely-grey-barnacle
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-yellow-zebra.sh
        container: qc.met_cozy-chestnut-chihuahua
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-seashell-paradise.sh
        container: qc.sec_baggy-amber-caracal
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-cerise-oyster.sh
        container: qc.sty_zippy-teal-ostrich
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-mauve-wolverine.sh
        container: qc.sty_tacky-amaranth-abyssinian
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-crimson-binturong.sh
        container: qc.ver_skimpy-mustard-worm
timeout: 1800
