config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-auburn-toad.sh
        container: qc.acc_nippy-ecru-kangaroo
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cardinal-discus.sh
        container: qc.doc_crabby-mauve-monkey
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-rose-iguana.sh
        container: qc.doc_snoopy-cyan-akbash
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-turquoise-paradise.sh
        container: qc.doc_shaky-cornflower-heron
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-mauve-forest.sh
        container: qc.lic_baggy-plum-orangutan
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-lime-budgerigar.sh
        container: qc.met_crappy-violet-hornet
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-orchid-dragon.sh
        container: qc.sec_dorky-persimmon-dugong
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-copper-crane.sh
        container: qc.sty_jumpy-cyan-cat
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-denim-dugong.sh
        container: qc.sty_stinky-khaki-tuatara
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cerulean-bracke.sh
        container: qc.ver_snoopy-silver-moorhen
timeout: 1800
