config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-crimson-kingfisher.sh
        container: qc.acc_greasy-chocolate-goose
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-yellow-coral.sh
        container: qc.doc_pretty-sangria-skunk
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-brown-akbash.sh
        container: qc.doc_trippy-turquoise-centipede
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-fuchsia-coral.sh
        container: qc.doc_cheeky-smalt-birman
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-beige-armadillo.sh
        container: qc.lic_hasty-scarlet-eel
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cerise-mau.sh
        container: qc.met_gamy-persimmon-indri
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-sepia-sheep.sh
        container: qc.sec_ready-aquamarine-reindeer
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-purple-spitz.sh
        container: qc.sty_sloppy-platinum-javanese
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-dandelion-sponge.sh
        container: qc.ver_seedy-charcoal-flamingo
timeout: 1800
