config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.3
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-indigo-liger.sh
        container: qc.acc_cozy-magenta-paradise
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-chestnut-robin.sh
        container: qc.doc_squirrely-platinum-neanderthal
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-violet-caracal.sh
        container: qc.doc_crappy-tan-wrasse
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-amethyst-tamarin.sh
        container: qc.doc_sickly-lime-dodo
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-salmon-rottweiler.sh
        container: qc.lic_shaky-cornflower-russel
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-grey-flounder.sh
        container: qc.met_skanky-taupe-fish
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-apricot-giraffe.sh
        container: qc.sec_lousy-mauve-blue
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-turquoise-caterpillar.sh
        container: qc.sty_wiggy-cobalt-boar
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-celadon-clam.sh
        container: qc.sty_whiny-emerald-turtle
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-heliotrope-forest.sh
        container: qc.ver_zippy-lemon-ladybird
timeout: 1800
