config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: dev-v1.4
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-rust-bird.sh
        container: qc.acc_ugly-magnolia-bongo
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-orchid-quoll.sh
        container: qc.doc_goopy-magenta-goat
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-xanthic-owl.sh
        container: qc.doc_surly-scarlet-hummingbird
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-grey-scorpion.sh
        container: qc.doc_lanky-magenta-bombay
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-gold-bat.sh
        container: qc.lic_seedy-khaki-binturong
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-vermilion-rat.sh
        container: qc.met_silly-xanthic-barb
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-silver-barnacle.sh
        container: qc.sec_hazy-scarlet-binturong
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-olivine-hamster.sh
        container: qc.sty_scaly-puce-guppy
      github.com/indigo-dc/udocker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-asparagus-cheetah.sh
        container: qc.sty_beady-indigo-macaw
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-gold-caracal.sh
        container: qc.sty_gamy-corn-cockroach
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-plum-ladybird.sh
        container: qc.ver_crabby-cinnabar-sponge
timeout: 5400
