config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: dev-v1.3.6
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-azure-mayfly.sh
        container: qc.acc_wiggy-red-audemer
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-russet-lynx.sh
        container: qc.doc_frumpy-silver-sheep
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-indigo-frigatebird.sh
        container: qc.doc_freaky-linen-anteater
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-mustard-koala.sh
        container: qc.doc_hazy-ruby-mongoose
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-sepia-eleuth.sh
        container: qc.lic_wiggy-orchid-booby
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-khaki-chinook.sh
        container: qc.met_pasty-indigo-ladybird
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-amaranth-magpie.sh
        container: qc.sec_scaly-flax-crab
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-persimmon-cuscus.sh
        container: qc.sty_wimpy-sangria-goat
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-brass-liger.sh
        container: qc.sty_gummy-ivory-fish
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-violet-terrier.sh
        container: qc.ver_wheezy-linen-gopher
timeout: 5400
