config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-teal-bear.sh
        container: qc.acc_randy-flax-antelope
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-orange-shrimp.sh
        container: qc.doc_scaly-platinum-woodpecker
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-magnolia-salamander.sh
        container: qc.doc_crabby-cerise-albatross
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-coral-capuchin.sh
        container: qc.doc_clammy-burgundy-blue
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-mustard-ladybird.sh
        container: qc.lic_breezy-charcoal-corgi
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-chestnut-jellyfish.sh
        container: qc.met_woozy-jade-kakapo
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-indigo-crane.sh
        container: qc.sec_chewy-sepia-mau
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-apricot-chihuahua.sh
        container: qc.sty_lumpy-alizarin-quail
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-russet-paradise.sh
        container: qc.sty_ugly-fuchsia-serval
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-champagne-duck.sh
        container: qc.ver_zippy-blue-bracke
timeout: 1800
