config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-platinum-anteater.sh
        container: qc.acc_sleepy-turquoise-beagle
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-champagne-capybara.sh
        container: qc.doc_goopy-cobalt-falcon
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-sepia-oyster.sh
        container: qc.doc_stealthy-copper-stoat
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-turquoise-shark.sh
        container: qc.doc_smelly-sepia-eagle
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-coral-beetle.sh
        container: qc.lic_craggy-black-tzu
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-viridian-frise.sh
        container: qc.met_hasty-purple-crab
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-linen-bordeaux.sh
        container: qc.sec_scanty-copper-ostrich
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-buff-manatee.sh
        container: qc.sty_woozy-russet-slug
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cerulean-quoll.sh
        container: qc.sty_craggy-olive-collie
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-aqua-coyote.sh
        container: qc.ver_hasty-magnolia-mau
timeout: 5400
