config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/style_tools
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-harlequin-dragonfly.sh
        container: qc.acc_lovely-xanthic-zebu
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-burgundy-magpie.sh
        container: qc.doc_pokey-cinnamon-chihuahua
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-eggplant-tiger.sh
        container: qc.doc_grumpy-beige-binturong
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-khaki-alligator.sh
        container: qc.doc_thirsty-burgundy-dachsbracke
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-ivory-bison.sh
        container: qc.lic_shaky-ruby-budgerigar
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.messy-harlequin-russel.sh
        container: qc.met_lanky-tomato-bird
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-vermilion-fousek.sh
        container: qc.sec_skinny-lemon-warthog
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-platinum-javanese.sh
        container: qc.sty_stealthy-orange-caterpillar
      github.com/indigo-dc/udocker pycodestyle:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-burgundy-eagle.sh
        container: qc.sty_smelly-razzmatazz-butterfly
      github.com/indigo-dc/udocker pylint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-salmon-panda.sh
        container: qc.sty_crabby-goldenrod-chinook
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-charcoal-sponge.sh
        container: qc.ver_flabby-maroon-ibis
timeout: 1800
