config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-green-rottweiler.sh
        container: qc.acc_chewy-chestnut-yak
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-goldenrod-caracal.sh
        container: qc.doc_foggy-periwinkle-rottweiler
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-charcoal-bongo.sh
        container: qc.doc_gloppy-pear-leopard
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-ruby-mau.sh
        container: qc.doc_breezy-olivine-bulldog
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-sepia-seahorse.sh
        container: qc.lic_queasy-lilac-baboon
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.silly-pumpkin-spoonbill.sh
        container: qc.met_crappy-burgundy-squirrel
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-green-camel.sh
        container: qc.sec_frumpy-emerald-drever
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.beady-salmon-worm.sh
        container: qc.sty_cloudy-cerise-tarantula
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-rose-beagle.sh
        container: qc.sty_gloppy-mustard-macaque
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-beige-ostrich.sh
        container: qc.ver_crabby-harlequin-turtle
timeout: 1800
