config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-ruby-jellyfish.sh
        container: qc.acc_nerdy-pear-cuscus
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-rust-zebu.sh
        container: qc.doc_ugly-cream-frog
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-ultramarine-lemur.sh
        container: qc.doc_skanky-ruby-seahorse
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-orchid-caterpillar.sh
        container: qc.doc_lumpy-gamboge-wildebeest
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-smalt-raccoon.sh
        container: qc.lic_snoopy-amber-civet
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-malachite-deer.sh
        container: qc.met_paltry-cardinal-bullfrog
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-taupe-butterfly.sh
        container: qc.sec_sloppy-brown-deer
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-chartreuse-dane.sh
        container: qc.sty_snazzy-plum-blue
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-burgundy-devil.sh
        container: qc.ver_homely-crimson-spitz
timeout: 1800
