config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: master
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-crimson-zorse.sh
        container: qc.acc_crabby-asparagus-chamois
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-olivine-crocodile.sh
        container: qc.doc_ugly-tangerine-flamingo
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-chocolate-dachshund.sh
        container: qc.doc_hilly-dandelion-terrier
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-red-crab.sh
        container: qc.doc_scaly-bronze-cichlid
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-burgundy-ostrich.sh
        container: qc.lic_woozy-thistle-wolf
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-bronze-axolotl.sh
        container: qc.met_snoopy-russet-crab
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-magnolia-peccary.sh
        container: qc.sec_shabby-sepia-wombat
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-carmine-bear.sh
        container: qc.sty_woolly-thistle-fowl
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-cream-chin.sh
        container: qc.ver_squirrely-yellow-javanese
timeout: 1800
