config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-sangria-ostrich.sh
        container: qc.acc_hasty-pear-manatee
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-olivine-bison.sh
        container: qc.doc_woozy-aquamarine-coyote
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-alizarin-fowl.sh
        container: qc.doc_gimpy-eggplant-turtle
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-khaki-gorilla.sh
        container: qc.doc_homey-copper-indri
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-violet-mouse.sh
        container: qc.lic_sleazy-violet-falcon
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-myrtle-ibis.sh
        container: qc.met_dorky-tomato-grasshopper
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-gold-lionfish.sh
        container: qc.sec_slaphappy-platinum-cuscus
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cream-rottweiler.sh
        container: qc.sty_snappy-zucchini-mouse
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-red-wolf.sh
        container: qc.sty_silly-cerulean-wallaby
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-lavender-sloth.sh
        container: qc.ver_snippy-goldenrod-tetra
timeout: 1800
