config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-mauve-wombat.sh
        container: qc.acc_grumpy-taupe-yak
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cornflower-rottweiler.sh
        container: qc.doc_hasty-chartreuse-tuatara
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-seashell-indri.sh
        container: qc.doc_goopy-bronze-iguana
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-linen-indri.sh
        container: qc.doc_slaphappy-emerald-orangutan
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-brown-chihuahua.sh
        container: qc.lic_pokey-copper-ray
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-rust-bee.sh
        container: qc.met_wiggy-indigo-swan
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-asparagus-impala.sh
        container: qc.sec_fuzzy-vermilion-tzu
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cinnabar-chicken.sh
        container: qc.sty_shaky-white-quokka
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-jade-mole.sh
        container: qc.sty_trippy-cobalt-cichlid
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-firebrick-tapir.sh
        container: qc.ver_sickly-lime-wolf
timeout: 5400
