config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-lavender-bulldog.sh
        container: qc.acc_flabby-brown-rattlesnake
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-chocolate-kangaroo.sh
        container: qc.doc_gummy-persimmon-chameleon
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-platinum-llama.sh
        container: qc.doc_crappy-flax-mammoth
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-malachite-mastiff.sh
        container: qc.doc_snazzy-violet-paradise
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-magnolia-oriole.sh
        container: qc.lic_whiny-pink-eleuth
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-asparagus-deer.sh
        container: qc.met_randy-dandelion-cuscus
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-platinum-hound.sh
        container: qc.sec_muggy-white-kakapo
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-smalt-turtle.sh
        container: qc.sty_pasty-cardinal-dane
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-indigo-civet.sh
        container: qc.sty_nippy-sapphire-wallaby
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-maroon-lion.sh
        container: qc.ver_breezy-grey-woodlouse
timeout: 1800
